"""add_sentiment_tables

Revision ID: 4da26d696e21
Revises: e9073a709315
Create Date: 2026-02-11 11:11:07.018080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da26d696e21'
down_revision: Union[str, Sequence[str], None] = 'e9073a709315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_comments',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Unique comment ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='Comment text content'),
    sa.Column('source_platform', sa.String(length=20), nullable=False, comment='Source platform: eastmoney/xueqiu/10jqka'),
    sa.Column('stock_code', sa.String(length=10), nullable=True, comment='Related stock code, NULL for general market discussion'),
    sa.Column('author_nickname', sa.String(length=100), nullable=True, comment='Author nickname'),
    sa.Column('published_time', sa.DateTime(), nullable=False, comment='Comment publish time'),
    sa.Column('content_hash', sa.String(length=32), nullable=False, comment='MD5 hash of content for deduplication'),
    sa.Column('sentiment_label', sa.String(length=10), nullable=True, comment='Sentiment label: fear/greed/neutral'),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='Sentiment intensity score (0-100)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    with op.batch_alter_table('sentiment_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_comments_published_time'), ['published_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_comments_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_comments_stock_code'), ['stock_code'], unique=False)
        batch_op.create_index('ix_sentiment_comments_stock_time', ['stock_code', 'published_time'], unique=False)

    op.create_table('sentiment_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Unique snapshot ID'),
    sa.Column('stock_code', sa.String(length=10), nullable=True, comment='Stock code, NULL for overall market'),
    sa.Column('index_value', sa.Float(), nullable=False, comment='Composite sentiment index (0-100)'),
    sa.Column('comment_sentiment_score', sa.Float(), nullable=True, comment='Comment sentiment sub-score (0-100)'),
    sa.Column('baidu_vote_score', sa.Float(), nullable=True, comment='Baidu vote sub-score (0-100)'),
    sa.Column('akshare_aggregate_score', sa.Float(), nullable=True, comment='AKShare aggregate sub-score (0-100)'),
    sa.Column('news_sentiment_score', sa.Float(), nullable=True, comment='News sentiment sub-score (0-100)'),
    sa.Column('margin_trading_score', sa.Float(), nullable=True, comment='Margin trading sub-score (0-100)'),
    sa.Column('fear_ratio', sa.Float(), nullable=True, comment='Fear comment ratio'),
    sa.Column('greed_ratio', sa.Float(), nullable=True, comment='Greed comment ratio'),
    sa.Column('neutral_ratio', sa.Float(), nullable=True, comment='Neutral comment ratio'),
    sa.Column('sample_count', sa.Integer(), nullable=True, comment='Comment sample count'),
    sa.Column('data_source_availability', sa.Text(), nullable=True, comment='JSON: {source_id: bool} availability map'),
    sa.Column('label', sa.String(length=20), nullable=False, comment='Sentiment label: extreme_fear/fear/neutral/greed/extreme_greed'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='Snapshot timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentiment_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_snapshots_snapshot_time'), ['snapshot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_snapshots_stock_code'), ['stock_code'], unique=False)
        batch_op.create_index('ix_sentiment_snapshots_stock_time', ['stock_code', 'snapshot_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentiment_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_sentiment_snapshots_stock_time')
        batch_op.drop_index(batch_op.f('ix_sentiment_snapshots_stock_code'))
        batch_op.drop_index(batch_op.f('ix_sentiment_snapshots_snapshot_time'))

    op.drop_table('sentiment_snapshots')
    with op.batch_alter_table('sentiment_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_sentiment_comments_stock_time')
        batch_op.drop_index(batch_op.f('ix_sentiment_comments_stock_code'))
        batch_op.drop_index(batch_op.f('ix_sentiment_comments_source_platform'))
        batch_op.drop_index(batch_op.f('ix_sentiment_comments_published_time'))

    op.drop_table('sentiment_comments')
    # ### end Alembic commands ###
