"""initial

Revision ID: e9073a709315
Revises: 
Create Date: 2026-02-10 17:35:16.133619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9073a709315'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_analysis_results',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Unique analysis result ID'),
    sa.Column('topic', sa.Text(), nullable=True, comment='Analysis topic (user input)'),
    sa.Column('news_titles', sa.Text(), nullable=True, comment='JSON array of input news titles'),
    sa.Column('summary', sa.Text(), nullable=True, comment='News summary'),
    sa.Column('impact_analysis', sa.Text(), nullable=True, comment='Impact analysis'),
    sa.Column('bull_argument', sa.Text(), nullable=True, comment='Bull case argument (aggressive bullish stance)'),
    sa.Column('bear_argument', sa.Text(), nullable=True, comment='Bear case argument (sharp bearish stance)'),
    sa.Column('debate_dialogue', sa.Text(), nullable=True, comment='Bull vs Bear debate dialogue'),
    sa.Column('controversial_conclusion', sa.Text(), nullable=True, comment='Controversial conclusion (clickbait style)'),
    sa.Column('stance', sa.String(length=10), nullable=True, comment='Final stance: bull or bear'),
    sa.Column('risk_warning', sa.Text(), nullable=True, comment='Risk warning / disclaimer'),
    sa.Column('sentiment_context', sa.Text(), nullable=True, comment='JSON: Sentiment data snapshot at analysis time'),
    sa.Column('cache_hit', sa.Boolean(), nullable=True, comment='Whether result was from cache'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_analysis_results_created_at'), ['created_at'], unique=False)

    op.create_table('stock_sector_mapping',
    sa.Column('stock_code', sa.String(length=10), nullable=False, comment='Stock code (e.g., 600519)'),
    sa.Column('stock_name', sa.String(length=50), nullable=False, comment='Stock name (e.g., 贵州茅台)'),
    sa.Column('sector_name', sa.String(length=50), nullable=True, comment='Sector name (e.g., 白酒)'),
    sa.Column('industry_name', sa.String(length=50), nullable=True, comment='Industry name (e.g., 食品饮料)'),
    sa.Column('desensitized_label', sa.String(length=100), nullable=True, comment='Medium desensitization label (e.g., 某白酒龙头)'),
    sa.Column('pinyin_abbr', sa.String(length=10), nullable=True, comment='Pinyin abbreviation for light desensitization (e.g., GZMT)'),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True, comment='Market cap rank within industry'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('stock_code')
    )
    with op.batch_alter_table('stock_sector_mapping', schema=None) as batch_op:
        batch_op.create_index('ix_stock_sector_mapping_stock_name', ['stock_name'], unique=False)

    op.create_table('social_content',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Unique content ID'),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='Target platform: xhs/weibo/xueqiu/zhihu'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='Content type: analysis/daily_report'),
    sa.Column('title', sa.Text(), nullable=True, comment='Content title (for Xiaohongshu/Xueqiu)'),
    sa.Column('body', sa.Text(), nullable=False, comment='Content body text'),
    sa.Column('tags', sa.Text(), nullable=True, comment='JSON array of hashtags'),
    sa.Column('image_urls', sa.Text(), nullable=True, comment='JSON array of image URLs'),
    sa.Column('desensitization_level', sa.String(length=10), nullable=True, comment='Desensitization level: light/medium/heavy/none'),
    sa.Column('original_content', sa.Text(), nullable=True, comment='Original content before desensitization'),
    sa.Column('user_acknowledged_risk', sa.Boolean(), nullable=True, comment="User acknowledged risk when choosing 'none' desensitization"),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: draft/published'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='Publication timestamp'),
    sa.Column('source_analysis_id', sa.String(length=64), nullable=True, comment='Related analysis result ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Creation timestamp'),
    sa.ForeignKeyConstraint(['source_analysis_id'], ['stock_analysis_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_content_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_content_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_content_source_analysis_id'), ['source_analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_content_source_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_social_content_platform'))
        batch_op.drop_index(batch_op.f('ix_social_content_created_at'))

    op.drop_table('social_content')
    with op.batch_alter_table('stock_sector_mapping', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_sector_mapping_stock_name')

    op.drop_table('stock_sector_mapping')
    with op.batch_alter_table('stock_analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_analysis_results_created_at'))

    op.drop_table('stock_analysis_results')
    # ### end Alembic commands ###
